# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FleaMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FleaMarket
    pod 'Parse'
    pod 'AlamofireImage'

  target 'FleaMarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FleaMarketUITests' do
    # Pods for testing
  end

end
